version: '3.8'

services:
  web:
    build: .
    container_name: ldview
    restart: unless-stopped
    ports:
      - "8000:8000"
    # volumes:
    #   - type: bind
    #     source: ./logs
    #     target: /var/log/ldview
    # environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
